### ISSUE TITLE
댓글 버그FIX & 댓글 서버리스폰스 수정

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/Wote#178]
## 📌 Issue
현재 댓글이 어느순간 갑자기 아무것도 안보이는 현상 발생
댓글의 Flow가 자연스럽지 않음
서버로부터 오는 response에 ban이 추가될예정

## 📝 To-do

- [x] 댓글의 버그 찾기(어느 환경에서 나는지)
- [x] 댓글의 response 바뀐거 수정
- [ ] 댓글의 UI수정할수 있으면 해보기
- [ ] ban일 경우도 추가
