### ISSUE TITLE
버그 fix

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/Wote#179]
## 📌 Issue

마이페이지 total 개수 수정
버그 fix

## 📝 To-do

- [x] 마이페이지 total 개수 반영
- [x] 메인뷰 새로고침 방법 추가
- [x] 동시 투표 막기
